development:
  adapter:  postgresql
  encoding: utf8
  database: tolkin_rails
  username: tolkin2
  password: d28xCvJlie28op2769dMnxli87379aAQweq788kj27
  pool: 5
  timeout: 5000

test:
  adapter:  postgresql
  encoding: utf8
  database: tolkin_testing
  username: tolkin2
  password: d28xCvJlie28op2769dMnxli87379aAQweq788kj27
  pool: 5
  timeout: 5000

production:
  adapter:  postgresql
  encoding: utf8
  database: tolkin_rails
  username: tolkin2
  password: d28xCvJlie28op2769dMnxli87379aAQweq788kj27
  pool: 5
  timeout: 5000
